// Ingredient aliases - maps variations to canonical form
// This handles synonyms, brand names, and common variations

export const INGREDIENT_ALIASES: Record<string, string> = {
  // Starches
  'cornflour': 'cornstarch',
  'corn flour': 'cornstarch',
  'corn starch': 'cornstarch',
  
  // Herbs - fresh/dried variations
  'coriander': 'cilantro',
  'fresh coriander': 'cilantro',
  'coriander leaves': 'cilantro',
  'chinese parsley': 'cilantro',
  'fresh cilantro': 'cilantro',
  'cilantro leaves': 'cilantro',
  
  'spring onion': 'green onion',
  'spring onions': 'green onion',
  'scallion': 'green onion',
  'scallions': 'green onion',
  'green onions': 'green onion',
  
  'rocket': 'arugula',
  'rocket lettuce': 'arugula',
  
  'courgette': 'zucchini',
  'courgettes': 'zucchini',
  
  'aubergine': 'eggplant',
  'aubergines': 'eggplant',
  
  'capsicum': 'bell pepper',
  'sweet pepper': 'bell pepper',
  
  // Sugars
  'caster sugar': 'sugar',
  'castor sugar': 'sugar',
  'granulated sugar': 'sugar',
  'white sugar': 'sugar',
  'superfine sugar': 'sugar',
  'regular sugar': 'sugar',
  
  'powdered sugar': 'confectioners sugar',
  'icing sugar': 'confectioners sugar',
  
  'demerara sugar': 'brown sugar',
  'muscovado sugar': 'brown sugar',
  'dark brown sugar': 'brown sugar',
  'light brown sugar': 'brown sugar',
  
  // Flours
  'all-purpose flour': 'flour',
  'all purpose flour': 'flour',
  'ap flour': 'flour',
  'plain flour': 'flour',
  'white flour': 'flour',
  'unbleached flour': 'flour',
  'bleached flour': 'flour',
  'self-raising flour': 'flour',
  'self raising flour': 'flour',
  'self-rising flour': 'flour',
  'self rising flour': 'flour',

  'wholemeal flour': 'whole wheat flour',
  'wholewheat flour': 'whole wheat flour',
  
  // Dairy
  'heavy cream': 'heavy whipping cream',
  'whipping cream': 'heavy whipping cream',
  'double cream': 'heavy whipping cream',
  'thickened cream': 'heavy whipping cream',
  
  'single cream': 'light cream',
  'pouring cream': 'light cream',
  
  'natural yogurt': 'plain yogurt',
  'natural yoghurt': 'plain yogurt',
  'plain yoghurt': 'plain yogurt',
  'greek yoghurt': 'greek yogurt',
  'plain greek yogurt': 'greek yogurt',
  'plain greek yoghurt': 'greek yogurt',
  'full fat greek yogurt': 'greek yogurt',
  'low fat greek yogurt': 'greek yogurt',
  'fat free greek yogurt': 'greek yogurt',
  'nonfat greek yogurt': 'greek yogurt',
  
  'salted butter': 'butter',
  'unsalted butter': 'butter',
  'softened butter': 'butter',
  'melted butter': 'butter',
  'cold butter': 'butter',
  'room temperature butter': 'butter',
  
  // Eggs
  'large egg': 'egg',
  'large eggs': 'egg',
  'medium egg': 'egg',
  'medium eggs': 'egg',
  'eggs': 'egg',
  'whole egg': 'egg',
  'whole eggs': 'egg',
  'free range egg': 'egg',
  'free range eggs': 'egg',
  
  // Cheese
  'parmesan cheese': 'parmesan',
  'parmigiano reggiano': 'parmesan',
  'parmigiano-reggiano': 'parmesan',
  'parmigiano': 'parmesan',
  'parm': 'parmesan',
  'grated parmesan': 'parmesan',
  'shredded parmesan': 'parmesan',
  'freshly grated parmesan': 'parmesan',
  'pecorino romano': 'pecorino',
  
  'cheddar cheese': 'cheddar',
  'sharp cheddar': 'cheddar',
  'mild cheddar': 'cheddar',
  'shredded cheddar': 'cheddar',
  'grated cheddar': 'cheddar',
  
  'mozzarella cheese': 'mozzarella',
  'fresh mozzarella': 'mozzarella',
  'shredded mozzarella': 'mozzarella',
  
  'cream cheese': 'cream cheese',
  'philadelphia': 'cream cheese',
  
  // Milk
  'whole milk': 'milk',
  'full fat milk': 'milk',
  '2% milk': 'milk',
  'reduced fat milk': 'milk',
  'skim milk': 'milk',
  'skimmed milk': 'milk',
  'low fat milk': 'milk',
  'fat free milk': 'milk',
  'semi-skimmed milk': 'milk',
  
  // Oils
  'extra virgin olive oil': 'olive oil',
  'extra-virgin olive oil': 'olive oil',
  'evoo': 'olive oil',
  'light olive oil': 'olive oil',
  
  'vegetable oil': 'neutral oil',
  'canola oil': 'neutral oil',
  'rapeseed oil': 'neutral oil',
  'sunflower oil': 'neutral oil',
  'corn oil': 'neutral oil',
  'cooking oil': 'neutral oil',
  'oil for frying': 'neutral oil',
  'frying oil': 'neutral oil',
  'oil': 'neutral oil',
  
  // Vinegars
  'white wine vinegar': 'white wine vinegar',
  'red wine vinegar': 'red wine vinegar',
  'balsamic vinegar': 'balsamic vinegar',
  'aged balsamic': 'balsamic vinegar',
  'apple cider vinegar': 'apple cider vinegar',
  'cider vinegar': 'apple cider vinegar',
  'rice vinegar': 'rice vinegar',
  'rice wine vinegar': 'rice vinegar',

  // Cooking Wines
  'red wine': 'red wine',
  'dry red wine': 'red wine',
  'red cooking wine': 'red wine',
  'white wine': 'white wine',
  'dry white wine': 'white wine',
  'white cooking wine': 'white wine',
  'cooking wine': 'white wine',
  'sherry': 'sherry',
  'cooking sherry': 'sherry',
  'dry sherry': 'sherry',
  'marsala': 'marsala wine',
  'marsala wine': 'marsala wine',

  // Broths/Stocks
  'chicken broth': 'chicken stock',
  'chicken stock': 'chicken stock',
  'low sodium chicken broth': 'chicken stock',
  'low-sodium chicken broth': 'chicken stock',
  
  'beef broth': 'beef stock',
  'beef stock': 'beef stock',
  'low sodium beef broth': 'beef stock',
  
  'vegetable broth': 'vegetable stock',
  'vegetable stock': 'vegetable stock',
  'veggie broth': 'vegetable stock',
  
  // Tomatoes
  'canned tomatoes': 'canned tomatoes',
  'tinned tomatoes': 'canned tomatoes',
  'canned chopped tomatoes': 'canned tomatoes',
  'canned diced tomatoes': 'canned tomatoes',
  'diced tomatoes': 'canned tomatoes',
  'chopped tomatoes': 'canned tomatoes',
  'crushed tomatoes': 'canned tomatoes',
  'canned crushed tomatoes': 'canned tomatoes',
  'canned peeled tomatoes': 'canned tomatoes',
  'whole peeled tomatoes': 'canned tomatoes',
  'whole tomatoes': 'canned tomatoes',
  'san marzano tomatoes': 'canned tomatoes',
  'plum tomatoes': 'canned tomatoes',
  
  'tomato paste': 'tomato paste',
  'tomato puree': 'tomato paste',
  'tomato concentrate': 'tomato paste',
  'double concentrate tomato': 'tomato paste',
  
  // Seasonings
  'kosher salt': 'salt',
  'sea salt': 'salt',
  'table salt': 'salt',
  'fine salt': 'salt',
  'coarse salt': 'salt',
  'flaky salt': 'salt',
  'maldon salt': 'salt',
  
  'black pepper': 'pepper',
  'ground black pepper': 'pepper',
  'freshly ground black pepper': 'pepper',
  'ground pepper': 'pepper',
  'cracked black pepper': 'pepper',
  'freshly cracked pepper': 'pepper',
  
  'salt and pepper': 'salt',
  'salt & pepper': 'salt',
  's&p': 'salt',
  
  // Garlic
  'garlic cloves': 'garlic',
  'garlic clove': 'garlic',
  'cloves garlic': 'garlic',
  'clove garlic': 'garlic',
  'minced garlic': 'garlic',
  'fresh garlic': 'garlic',
  'crushed garlic': 'garlic',
  'head of garlic': 'garlic',
  'garlic head': 'garlic',
  'heads of garlic': 'garlic',
  'whole garlic': 'garlic',
  
  // Onions
  'onions': 'onion',
  'yellow onion': 'onion',
  'yellow onions': 'onion',
  'white onion': 'onion',
  'white onions': 'onion',
  'brown onion': 'onion',
  'brown onions': 'onion',
  'sweet onion': 'onion',
  'vidalia onion': 'onion',
  
  'red onion': 'red onion',
  'red onions': 'red onion',
  'purple onion': 'red onion',
  
  // Common vegetables
  'tomatoes': 'tomato',
  'fresh tomatoes': 'tomato',
  'ripe tomatoes': 'tomato',
  'roma tomatoes': 'tomato',
  'roma tomato': 'tomato',
  'vine tomatoes': 'tomato',
  'beefsteak tomato': 'tomato',

  'cucumbers': 'cucumber',
  'english cucumber': 'cucumber',
  'english cucumbers': 'cucumber',
  'seedless cucumber': 'cucumber',
  'seedless cucumbers': 'cucumber',
  'hothouse cucumber': 'cucumber',
  'hothouse cucumbers': 'cucumber',
  'mini cucumber': 'cucumber',
  'mini cucumbers': 'cucumber',
  'persian cucumber': 'cucumber',
  'persian cucumbers': 'cucumber',

  'potatoes': 'potato',
  'russet potatoes': 'potato',
  'russet potato': 'potato',
  'baking potatoes': 'potato',
  'baking potato': 'potato',
  'white potatoes': 'potato',
  'white potato': 'potato',
  'medium potato': 'potato',
  'medium potatoes': 'potato',
  'large potato': 'potato',
  'large potatoes': 'potato',
  'small potato': 'potato',
  'small potatoes': 'potato',
  'red potato': 'potato',
  'red potatoes': 'potato',
  'baby potato': 'potato',
  'baby potatoes': 'potato',
  'new potato': 'potato',
  'new potatoes': 'potato',
  
  'yukon gold potatoes': 'yukon gold potato',
  'yukon gold': 'yukon gold potato',
  'gold potatoes': 'yukon gold potato',
  
  'carrots': 'carrot',
  'large carrots': 'carrot',
  'medium carrots': 'carrot',
  
  'celery stalks': 'celery',
  'celery stalk': 'celery',
  'stalks celery': 'celery',
  'ribs celery': 'celery',
  'celery ribs': 'celery',
  'celery rib': 'celery',
  'celery stick': 'celery',
  'celery sticks': 'celery',
  
  // Peppers
  'bell pepper': 'bell pepper',
  'bell peppers': 'bell pepper',
  'red bell pepper': 'red bell pepper',
  'red bell peppers': 'red bell pepper',
  'red pepper': 'red bell pepper',
  'green bell pepper': 'green bell pepper',
  'green bell peppers': 'green bell pepper',
  'green pepper': 'green bell pepper',
  'yellow bell pepper': 'yellow bell pepper',
  'orange bell pepper': 'orange bell pepper',
  
  // Citrus
  'lemons': 'lemon',
  'fresh lemon': 'lemon',
  'limes': 'lime',
  'fresh lime': 'lime',
  
  'lemon juice': 'lemon juice',
  'fresh lemon juice': 'lemon juice',
  'lime juice': 'lime juice',
  'fresh lime juice': 'lime juice',
  
  'lemon zest': 'lemon zest',
  'zest of lemon': 'lemon zest',
  'lime zest': 'lime zest',
  'zest of lime': 'lime zest',
  
  // Herbs (fresh/dried treated same for shopping)
  'fresh parsley': 'parsley',
  'flat leaf parsley': 'parsley',
  'flat-leaf parsley': 'parsley',
  'italian parsley': 'parsley',
  'curly parsley': 'parsley',
  'chopped parsley': 'parsley',
  
  'fresh basil': 'basil',
  'basil leaves': 'basil',
  'fresh basil leaves': 'basil',
  'thai basil': 'thai basil',
  
  'fresh thyme': 'thyme',
  'thyme leaves': 'thyme',
  'thyme sprigs': 'thyme',
  
  'fresh rosemary': 'rosemary',
  'rosemary leaves': 'rosemary',
  'rosemary sprigs': 'rosemary',
  
  'fresh oregano': 'oregano',
  'dried oregano': 'oregano',
  
  'fresh dill': 'dill',
  'dill weed': 'dill',
  
  'fresh mint': 'mint',
  'mint leaves': 'mint',
  'fresh mint leaves': 'mint',
  
  // Proteins
  'chicken breasts': 'chicken breast',
  'boneless chicken breasts': 'chicken breast',
  'boneless skinless chicken breasts': 'chicken breast',
  'boneless, skinless chicken breasts': 'chicken breast',
  'skinless chicken breast': 'chicken breast',
  
  'chicken thighs': 'chicken thigh',
  'boneless chicken thighs': 'chicken thigh',
  'boneless skinless chicken thighs': 'chicken thigh',
  'skinless chicken thighs': 'chicken thigh',
  
  'ground beef': 'ground beef',
  'minced beef': 'ground beef',
  'beef mince': 'ground beef',
  'lean ground beef': 'ground beef',
  'lean beef mince': 'ground beef',
  'lean mince': 'ground beef',
  'extra lean ground beef': 'ground beef',
  'extra lean beef mince': 'ground beef',
  'premium beef mince': 'ground beef',
  'regular ground beef': 'ground beef',
  '80/20 ground beef': 'ground beef',
  '85/15 ground beef': 'ground beef',
  '90/10 ground beef': 'ground beef',
  '93/7 ground beef': 'ground beef',
  'beef mince 500g': 'ground beef',
  'beef mince 250g': 'ground beef',

  'ground pork': 'ground pork',
  'pork mince': 'ground pork',
  'minced pork': 'ground pork',
  'lean pork mince': 'ground pork',

  'ground turkey': 'ground turkey',
  'turkey mince': 'ground turkey',
  'minced turkey': 'ground turkey',
  'lean turkey mince': 'ground turkey',

  'ground lamb': 'ground lamb',
  'lamb mince': 'ground lamb',
  'minced lamb': 'ground lamb',
  'lean lamb mince': 'ground lamb',

  'ground chicken': 'ground chicken',
  'chicken mince': 'ground chicken',
  'minced chicken': 'ground chicken',
  
  'bacon strips': 'bacon',
  'bacon slices': 'bacon',
  'streaky bacon': 'bacon',
  'rashers bacon': 'bacon',
  
  // Pasta
  'spaghetti pasta': 'spaghetti',
  'spaghetti noodles': 'spaghetti',
  'penne pasta': 'penne',
  'penne rigate': 'penne',
  'rigatoni pasta': 'rigatoni',
  'fettuccine pasta': 'fettuccine',
  'fettuccine noodles': 'fettuccine',
  'linguine pasta': 'linguine',
  'farfalle pasta': 'farfalle',
  'bow tie pasta': 'farfalle',
  
  // Rice
  'white rice': 'rice',
  'long grain rice': 'rice',
  'long-grain rice': 'rice',
  'long grain white rice': 'rice',
  'short grain rice': 'rice',
  'medium grain rice': 'rice',
  
  'jasmine rice': 'jasmine rice',
  'thai jasmine rice': 'jasmine rice',
  
  'basmati rice': 'basmati rice',
  'white basmati': 'basmati rice',
  'aged basmati': 'basmati rice',
  
  // Breads
  'bread crumbs': 'breadcrumbs',
  'dried breadcrumbs': 'breadcrumbs',
  'plain breadcrumbs': 'breadcrumbs',
  'italian breadcrumbs': 'breadcrumbs',
  
  'panko bread crumbs': 'panko',
  'panko breadcrumbs': 'panko',
  'japanese breadcrumbs': 'panko',
  
  // Soy products
  'soy sauce': 'soy sauce',
  'light soy sauce': 'soy sauce',
  'dark soy sauce': 'dark soy sauce',
  'low sodium soy sauce': 'soy sauce',
  'reduced sodium soy sauce': 'soy sauce',
  'tamari': 'soy sauce',
  'shoyu': 'soy sauce',
  
  // Asian ingredients
  'sesame oil': 'sesame oil',
  'toasted sesame oil': 'sesame oil',
  'dark sesame oil': 'sesame oil',
  
  'fish sauce': 'fish sauce',
  'thai fish sauce': 'fish sauce',
  'nam pla': 'fish sauce',
  
  'oyster sauce': 'oyster sauce',
  
  'hoisin sauce': 'hoisin sauce',
  'hoisin': 'hoisin sauce',
  
  'coconut milk': 'coconut milk',
  'full fat coconut milk': 'coconut milk',
  'light coconut milk': 'coconut milk',
  'coconut cream': 'coconut cream',
  
  // Baking
  'baking powder': 'baking powder',
  'baking soda': 'baking soda',
  'bicarbonate of soda': 'baking soda',
  'bicarb soda': 'baking soda',
  
  'vanilla extract': 'vanilla extract',
  'pure vanilla extract': 'vanilla extract',
  'vanilla essence': 'vanilla extract',
  
  'active dry yeast': 'yeast',
  'instant yeast': 'yeast',
  'dry yeast': 'yeast',
  'rapid rise yeast': 'yeast',
  
  // Nuts
  'almonds': 'almond',
  'whole almonds': 'almond',
  'sliced almonds': 'sliced almond',
  'slivered almonds': 'sliced almond',
  
  'walnuts': 'walnut',
  'walnut halves': 'walnut',
  'chopped walnuts': 'walnut',
  
  'pecans': 'pecan',
  'pecan halves': 'pecan',
  'chopped pecans': 'pecan',
  
  'peanuts': 'peanut',
  'roasted peanuts': 'peanut',
  'unsalted peanuts': 'peanut',
  
  'cashews': 'cashew',
  'cashew nuts': 'cashew',
  'raw cashews': 'cashew',
  'roasted cashews': 'cashew',
  
  'pine nuts': 'pine nut',
  'pignoli': 'pine nut',
  'pinoli': 'pine nut',

  // ========================================
  // International/Regional Variants
  // ========================================

  // Indian names (from CulinaryDB)
  'palak': 'spinach',
  'saag': 'spinach',
  'jeera': 'cumin',
  'zeera': 'cumin',
  'haldi': 'turmeric',
  'dhania': 'cilantro',
  'dhania powder': 'coriander powder',
  'methi': 'fenugreek',
  'methi leaves': 'fenugreek leaves',
  'kasuri methi': 'dried fenugreek leaves',
  'hing': 'asafoetida',
  'heeng': 'asafoetida',
  'kali mirch': 'black pepper',
  'lal mirch': 'red chili powder',
  'rai': 'mustard seeds',
  'sarson': 'mustard',
  'chana': 'chickpea',
  'chole': 'chickpea',
  'kabuli chana': 'chickpea',
  'masoor': 'red lentil',
  'masoor dal': 'red lentil',
  'urad': 'black lentil',
  'urad dal': 'black lentil',
  'moong': 'mung bean',
  'moong dal': 'mung bean',
  'toor dal': 'pigeon pea',
  'arhar dal': 'pigeon pea',
  'chana dal': 'split chickpea',
  'besan': 'chickpea flour',
  'gram flour': 'chickpea flour',
  'atta': 'whole wheat flour',
  'maida': 'flour',
  'ghee': 'ghee',
  'desi ghee': 'ghee',
  'clarified butter': 'ghee',
  'paneer': 'paneer',
  'cottage cheese': 'paneer',
  'dahi': 'yogurt',
  'curd': 'yogurt',
  'elaichi': 'cardamom',
  'green cardamom': 'cardamom',
  'black cardamom': 'black cardamom',
  'badi elaichi': 'black cardamom',
  'dalchini': 'cinnamon',
  'laung': 'cloves',
  'lavang': 'cloves',
  'jaiphal': 'nutmeg',
  'javitri': 'mace',
  'ajwain': 'carom seeds',
  'kalonji': 'nigella seeds',
  'saunf': 'fennel seeds',
  'til': 'sesame seeds',
  'imli': 'tamarind',
  'amchur': 'dried mango powder',
  'amchoor': 'dried mango powder',
  'garam masala': 'garam masala',

  // UK/Australian/British terms
  'swede': 'rutabaga',
  'neep': 'rutabaga',
  'mangetout': 'snow pea',
  'mange tout': 'snow pea',
  'cos lettuce': 'romaine',
  'celeriac': 'celery root',
  'broad beans': 'fava beans',
  'broad bean': 'fava beans',
  'runner beans': 'green beans',
  'french beans': 'green beans',
  'haricot beans': 'navy beans',
  'haricot vert': 'green beans',
  'haricots verts': 'green beans',
  'sultanas': 'golden raisins',
  'sultana': 'golden raisins',
  'currants': 'dried currants',
  'bicarb': 'baking soda',
  'beetroot': 'beet',
  'beetroots': 'beet',
  'spring greens': 'collard greens',
  'cavolo nero': 'tuscan kale',
  'black cabbage': 'tuscan kale',
  'marrow': 'zucchini',
  'vegetable marrow': 'zucchini',
  'treacle': 'molasses',
  'black treacle': 'molasses',
  'golden syrup': 'light corn syrup',
  'digestive biscuit': 'graham cracker',
  'digestives': 'graham cracker',
  'clotted cream': 'clotted cream',
  'creme fraiche': 'sour cream',
  'crème fraîche': 'sour cream',
  'rashers': 'bacon',
  'back bacon': 'canadian bacon',
  'gammon': 'ham',
  'mince': 'ground beef',

  // ========================================
  // Seafood
  // ========================================

  // Salmon
  'atlantic salmon': 'salmon',
  'sockeye salmon': 'salmon',
  'king salmon': 'salmon',
  'chinook salmon': 'salmon',
  'coho salmon': 'salmon',
  'wild salmon': 'salmon',
  'salmon fillet': 'salmon',
  'salmon fillets': 'salmon',
  'salmon steak': 'salmon',
  'fresh salmon': 'salmon',

  // Cod
  'cod fillet': 'cod',
  'cod fillets': 'cod',
  'pacific cod': 'cod',
  'atlantic cod': 'cod',
  'fresh cod': 'cod',
  'salt cod': 'salt cod',
  'bacalao': 'salt cod',
  'baccala': 'salt cod',

  // Tuna
  'ahi tuna': 'tuna',
  'yellowfin tuna': 'tuna',
  'albacore tuna': 'tuna',
  'bluefin tuna': 'tuna',
  'tuna steak': 'tuna',
  'tuna steaks': 'tuna',
  'fresh tuna': 'tuna',
  'sushi grade tuna': 'tuna',

  // Other fish
  'sea bass': 'bass',
  'striped bass': 'bass',
  'chilean sea bass': 'chilean sea bass',
  'branzino': 'branzino',
  'european sea bass': 'branzino',

  'tilapia fillet': 'tilapia',
  'tilapia fillets': 'tilapia',

  'halibut fillet': 'halibut',
  'halibut fillets': 'halibut',
  'pacific halibut': 'halibut',

  'mahi mahi': 'mahi mahi',
  'mahi-mahi': 'mahi mahi',
  'dorado': 'mahi mahi',
  'dolphinfish': 'mahi mahi',

  'swordfish steak': 'swordfish',
  'swordfish steaks': 'swordfish',

  'red snapper': 'snapper',
  'yellowtail snapper': 'snapper',
  'snapper fillet': 'snapper',

  'rainbow trout': 'trout',
  'steelhead trout': 'trout',
  'trout fillet': 'trout',

  'catfish fillet': 'catfish',
  'catfish fillets': 'catfish',

  'sardines': 'sardine',
  'fresh sardines': 'sardine',
  'canned sardines': 'canned sardines',

  'anchovies': 'anchovy',
  'anchovy fillets': 'anchovy',
  'canned anchovies': 'anchovy',

  // Shellfish - Shrimp
  'raw shrimp': 'shrimp',
  'cooked shrimp': 'shrimp',
  'prawns': 'shrimp',
  'king prawns': 'shrimp',
  'tiger prawns': 'shrimp',
  'large shrimp': 'shrimp',
  'jumbo shrimp': 'shrimp',
  'medium shrimp': 'shrimp',
  'small shrimp': 'shrimp',
  'shell-on shrimp': 'shrimp',
  'peeled shrimp': 'shrimp',
  'deveined shrimp': 'shrimp',
  'peeled and deveined shrimp': 'shrimp',
  'shrimp (peeled and deveined)': 'shrimp',

  // Shellfish - Other
  'sea scallops': 'scallops',
  'bay scallops': 'scallops',
  'diver scallops': 'scallops',
  'dry scallops': 'scallops',

  'littleneck clams': 'clams',
  'cherrystone clams': 'clams',
  'manila clams': 'clams',
  'razor clams': 'clams',
  'canned clams': 'canned clams',
  'clam juice': 'clam juice',

  'mussels': 'mussel',
  'fresh mussels': 'mussel',
  'pei mussels': 'mussel',
  'black mussels': 'mussel',
  'green lip mussels': 'mussel',

  'maine lobster': 'lobster',
  'lobster tail': 'lobster',
  'lobster tails': 'lobster',
  'spiny lobster': 'lobster',

  'dungeness crab': 'crab',
  'blue crab': 'crab',
  'king crab': 'crab',
  'lump crab': 'crab',
  'crab meat': 'crab',
  'crabmeat': 'crab',

  'squid': 'calamari',
  'calamari rings': 'calamari',
  'squid rings': 'calamari',

  'octopus': 'octopus',
  'baby octopus': 'octopus',

  // ========================================
  // Produce Varieties
  // ========================================

  // Mushrooms
  'white mushrooms': 'mushroom',
  'button mushrooms': 'mushroom',
  'white button mushrooms': 'mushroom',
  'mushrooms': 'mushroom',
  'cremini mushrooms': 'cremini',
  'creminis': 'cremini',
  'baby bella mushrooms': 'cremini',
  'baby bellas': 'cremini',
  'portobello mushrooms': 'portobello',
  'portabella mushrooms': 'portobello',
  'portabellas': 'portobello',
  'portobellos': 'portobello',
  'portobello caps': 'portobello',
  'shiitake mushrooms': 'shiitake',
  'shiitakes': 'shiitake',
  'fresh shiitake': 'shiitake',
  'dried shiitake': 'dried shiitake',
  'oyster mushrooms': 'oyster mushroom',
  'king oyster mushrooms': 'king oyster mushroom',
  'chanterelle mushrooms': 'chanterelle',
  'chanterelles': 'chanterelle',
  'porcini mushrooms': 'porcini',
  'dried porcini': 'dried porcini',
  'morel mushrooms': 'morel',
  'morels': 'morel',
  'enoki mushrooms': 'enoki',
  'maitake mushrooms': 'maitake',
  'hen of the woods': 'maitake',

  // Greens
  'baby spinach': 'spinach',
  'mature spinach': 'spinach',
  'spinach leaves': 'spinach',
  'fresh spinach': 'spinach',
  'kale leaves': 'kale',
  'curly kale': 'kale',
  'lacinato kale': 'lacinato kale',
  'tuscan kale': 'lacinato kale',
  'dinosaur kale': 'lacinato kale',
  'baby kale': 'kale',
  'swiss chard': 'chard',
  'rainbow chard': 'chard',
  'red chard': 'chard',
  'chard leaves': 'chard',
  'collard greens': 'collard greens',
  'collards': 'collard greens',
  'mustard greens': 'mustard greens',
  'turnip greens': 'turnip greens',
  'beet greens': 'beet greens',
  'dandelion greens': 'dandelion greens',
  'watercress': 'watercress',
  'baby arugula': 'arugula',
  'wild arugula': 'arugula',
  'arugula leaves': 'arugula',

  // Lettuce varieties
  'iceberg lettuce': 'lettuce',
  'head lettuce': 'lettuce',
  'butter lettuce': 'butter lettuce',
  'bibb lettuce': 'butter lettuce',
  'boston lettuce': 'butter lettuce',
  'butterhead lettuce': 'butter lettuce',
  'romaine lettuce': 'romaine',
  'romaine hearts': 'romaine',
  'little gem lettuce': 'little gem',
  'gem lettuce': 'little gem',
  'red leaf lettuce': 'red leaf lettuce',
  'green leaf lettuce': 'green leaf lettuce',
  'mixed greens': 'mixed greens',
  'spring mix': 'mixed greens',
  'mesclun': 'mixed greens',
  'salad greens': 'mixed greens',

  // Squash varieties
  'butternut squash': 'butternut squash',
  'butternut': 'butternut squash',
  'acorn squash': 'acorn squash',
  'delicata squash': 'delicata squash',
  'delicata': 'delicata squash',
  'spaghetti squash': 'spaghetti squash',
  'kabocha squash': 'kabocha',
  'kabocha': 'kabocha',
  'japanese pumpkin': 'kabocha',
  'hubbard squash': 'hubbard squash',
  'honeynut squash': 'honeynut squash',
  'yellow squash': 'yellow squash',
  'summer squash': 'yellow squash',
  'crookneck squash': 'yellow squash',
  'pattypan squash': 'pattypan squash',
  'zucchini squash': 'zucchini',
  'green zucchini': 'zucchini',
  'baby zucchini': 'zucchini',

  // ========================================
  // Spice Blends
  // ========================================

  'chinese five spice': 'five spice powder',
  'five-spice powder': 'five spice powder',
  'five spice': 'five spice powder',
  'chinese 5 spice': 'five spice powder',
  '5 spice powder': 'five spice powder',

  'garam masala powder': 'garam masala',

  'curry powder': 'curry powder',
  'madras curry powder': 'curry powder',
  'thai curry powder': 'curry powder',
  'hot curry powder': 'curry powder',
  'mild curry powder': 'curry powder',

  'italian seasoning': 'italian seasoning',
  'italian herb blend': 'italian seasoning',
  'italian herbs': 'italian seasoning',

  'herbes de provence': 'herbs de provence',
  'herbs de provence': 'herbs de provence',
  'provence herbs': 'herbs de provence',

  'taco seasoning': 'taco seasoning',
  'taco spice': 'taco seasoning',
  'taco spice mix': 'taco seasoning',

  'cajun seasoning': 'cajun seasoning',
  'cajun spice': 'cajun seasoning',
  'creole seasoning': 'cajun seasoning',
  'cajun spice blend': 'cajun seasoning',

  'old bay': 'old bay seasoning',
  'old bay seasoning': 'old bay seasoning',

  'za\'atar': 'zaatar',
  'zaatar': 'zaatar',
  'zatar': 'zaatar',

  'ras el hanout': 'ras el hanout',
  'ras-el-hanout': 'ras el hanout',

  'berbere': 'berbere',
  'berbere spice': 'berbere',

  'harissa': 'harissa',
  'harissa paste': 'harissa',
  'harissa powder': 'harissa',

  'baharat': 'baharat',
  'middle eastern spice blend': 'baharat',

  'shichimi togarashi': 'shichimi togarashi',
  'shichimi': 'shichimi togarashi',
  'togarashi': 'shichimi togarashi',
  'japanese seven spice': 'shichimi togarashi',

  'furikake': 'furikake',
  'rice seasoning': 'furikake',

  'chili powder': 'chili powder',
  'chile powder': 'chili powder',
  'ancho chili powder': 'ancho chili powder',
  'chipotle powder': 'chipotle powder',
  'chipotle chili powder': 'chipotle powder',
  'cayenne powder': 'cayenne pepper',
  'ground cayenne': 'cayenne pepper',

  'adobo seasoning': 'adobo seasoning',
  'sazon': 'sazon seasoning',
  'sazon seasoning': 'sazon seasoning',

  'jerk seasoning': 'jerk seasoning',
  'jamaican jerk': 'jerk seasoning',
  'jerk spice': 'jerk seasoning',

  'pumpkin pie spice': 'pumpkin pie spice',
  'pumpkin spice': 'pumpkin pie spice',

  'apple pie spice': 'apple pie spice',

  'everything bagel seasoning': 'everything bagel seasoning',
  'everything seasoning': 'everything bagel seasoning',

  // ========================================
  // Legumes & Grains
  // ========================================

  // White beans
  'cannellini beans': 'white beans',
  'cannellini': 'white beans',
  'great northern beans': 'white beans',
  'navy beans': 'white beans',
  'white kidney beans': 'white beans',
  'white beans': 'white beans',

  // Other beans
  'pinto beans': 'pinto beans',
  'kidney beans': 'kidney beans',
  'red kidney beans': 'kidney beans',
  'dark red kidney beans': 'kidney beans',
  'light red kidney beans': 'kidney beans',
  'black beans': 'black beans',
  'black turtle beans': 'black beans',
  'canned black beans': 'black beans',

  // Chickpeas
  'garbanzo beans': 'chickpeas',
  'chickpeas': 'chickpeas',
  'canned chickpeas': 'chickpeas',
  'dried chickpeas': 'chickpeas',

  // Lentils
  'green lentils': 'lentils',
  'brown lentils': 'lentils',
  'french lentils': 'french lentils',
  'puy lentils': 'french lentils',
  'du puy lentils': 'french lentils',
  'beluga lentils': 'black lentils',
  'black lentils': 'black lentils',
  'red lentils': 'red lentils',
  'yellow lentils': 'yellow lentils',
  'split red lentils': 'red lentils',
  'split lentils': 'lentils',

  // Grains - Barley
  'pearled barley': 'barley',
  'pearl barley': 'barley',
  'hulled barley': 'barley',
  'barley': 'barley',

  // Grains - Oats
  'steel cut oats': 'oats',
  'steel-cut oats': 'oats',
  'rolled oats': 'oats',
  'old fashioned oats': 'oats',
  'old-fashioned oats': 'oats',
  'quick oats': 'oats',
  'quick cooking oats': 'oats',
  'instant oats': 'oats',
  'oat flakes': 'oats',

  // Grains - Others
  'farro': 'farro',
  'pearled farro': 'farro',
  'semi-pearled farro': 'farro',

  'bulgur wheat': 'bulgur',
  'bulgur': 'bulgur',
  'cracked wheat': 'bulgur',
  'bulghur': 'bulgur',

  'freekeh': 'freekeh',
  'cracked freekeh': 'freekeh',

  'quinoa': 'quinoa',
  'white quinoa': 'quinoa',
  'red quinoa': 'quinoa',
  'tri-color quinoa': 'quinoa',
  'tricolor quinoa': 'quinoa',

  'couscous': 'couscous',
  'israeli couscous': 'israeli couscous',
  'pearl couscous': 'israeli couscous',
  'ptitim': 'israeli couscous',

  'polenta': 'polenta',
  'instant polenta': 'polenta',
  'cornmeal': 'cornmeal',
  'corn meal': 'cornmeal',
  'yellow cornmeal': 'cornmeal',
  'white cornmeal': 'cornmeal',
  'coarse cornmeal': 'cornmeal',
  'fine cornmeal': 'cornmeal',

  'grits': 'grits',
  'stone ground grits': 'grits',
  'hominy grits': 'grits',

  'buckwheat': 'buckwheat',
  'buckwheat groats': 'buckwheat',
  'kasha': 'buckwheat',

  'millet': 'millet',

  'amaranth': 'amaranth',

  'teff': 'teff',
  'teff grain': 'teff',

  'wild rice': 'wild rice',
  'wild rice blend': 'wild rice',

  'arborio rice': 'arborio rice',
  'carnaroli rice': 'arborio rice',
  'risotto rice': 'arborio rice',

  'sushi rice': 'sushi rice',
  'short grain japanese rice': 'sushi rice',
  'calrose rice': 'sushi rice',

  // Bakery items that contain descriptor words
  'english muffin': 'english muffin',
  'english muffins': 'english muffin',
};

// Words to strip from ingredient names (don't affect shopping)
export const DESCRIPTORS_TO_REMOVE = [
  'fresh',
  'freshly',
  'dried',
  'ground',
  'minced',
  'chopped',
  'diced',
  'sliced',
  'cubed',
  'julienned',
  'shredded',
  'grated',
  'crushed',
  'mashed',
  'pureed',
  'melted',
  'softened',
  'room temperature',
  'cold',
  'warm',
  'hot',
  'frozen',
  'thawed',
  'cooked',
  'raw',
  'ripe',
  'unripe',
  'peeled',
  'unpeeled',
  'seeded',
  'seedless',
  'deseeded',
  'cored',
  'trimmed',
  'cleaned',
  'washed',
  'rinsed',
  'drained',
  'packed',
  'loosely packed',
  'firmly packed',
  'lightly packed',
  'tightly packed',
  'divided',
  'separated',
  'beaten',
  'whisked',
  'sifted',
  'toasted',
  'roasted',
  'blanched',
  'optional',
  'to taste',
  'as needed',
  'for serving',
  'for garnish',
  'for topping',
  'of choice',
  'your choice',
  'approximately',
  'about',
  'roughly',
  'finely',
  'coarsely',
  'thinly',
  'thickly',
  'medium',
  'small',
  'large',
  'extra large',
  'jumbo',
  'organic',
  'natural',
  'pure',
  'quality',
  'good quality',
  'high quality',
  'best quality',
  'homemade',
  'store bought',
  'store-bought',
  'prepared',
  'ready made',
  'pre-made',
  'plus more',
  'plus extra',
  'heaping',
  'heaped',
  'level',
  'rounded',
  'scant',
  'generous',
  // Size/count descriptors for produce
  'sized',
  'stick',
  'sticks',
  'head',
  'head of',
  'english',
  'bunch',
  'bunch of',
  'clove',
  'cloves',
  'sprig',
  'sprigs',
  'sprig of',
  'sprigs of',
  'rib',
  'ribs',
  'stalk',
  'stalks',
  // Descriptive adjectives that cause false category matches
  'buttery',
  'creamy',
  'cheesy',
  'milky',
  'eggy',
  'meaty',
  'fishy',
  'nutty',
  'fruity',
  'spicy',
  'savory',
  'savoury',
  'sweet',
  'sour',
  'tangy',
  'zesty',
  'smoky',
  'crispy',
  'crunchy',
  'tender',
  'juicy',
  'rich',
  'light',
  'heavy',
  'thick',
  'thin',
  'smooth',
  'chunky',
  'hearty',
  'delicate',
  'bold',
  'mild',
  'strong',
  'subtle',
];
