// Ingredient category lookup table
// Maps canonical/normalized ingredient names to shopping categories
// This provides explicit, reliable categorization without regex substring issues

export const INGREDIENT_CATEGORIES: Record<string, string> = {
  // ========================================
  // PRODUCE
  // ========================================

  // Vegetables
  'olive': 'Produce',
  'tomato': 'Produce',
  'onion': 'Produce',
  'red onion': 'Produce',
  'garlic': 'Produce',
  'potato': 'Produce',
  'yukon gold potato': 'Produce',
  'sweet potato': 'Produce',
  'carrot': 'Produce',
  'celery': 'Produce',
  'celery root': 'Produce',
  'lettuce': 'Produce',
  'romaine': 'Produce',
  'butter lettuce': 'Produce',
  'little gem': 'Produce',
  'red leaf lettuce': 'Produce',
  'green leaf lettuce': 'Produce',
  'mixed greens': 'Produce',
  'spinach': 'Produce',
  'kale': 'Produce',
  'lacinato kale': 'Produce',
  'chard': 'Produce',
  'collard greens': 'Produce',
  'mustard greens': 'Produce',
  'turnip greens': 'Produce',
  'beet greens': 'Produce',
  'dandelion greens': 'Produce',
  'watercress': 'Produce',
  'arugula': 'Produce',
  'mushroom': 'Produce',
  'cremini': 'Produce',
  'portobello': 'Produce',
  'shiitake': 'Produce',
  'oyster mushroom': 'Produce',
  'king oyster mushroom': 'Produce',
  'chanterelle': 'Produce',
  'porcini': 'Produce',
  'morel': 'Produce',
  'enoki': 'Produce',
  'maitake': 'Produce',
  'cucumber': 'Produce',
  'bell pepper': 'Produce',
  'red bell pepper': 'Produce',
  'green bell pepper': 'Produce',
  'yellow bell pepper': 'Produce',
  'orange bell pepper': 'Produce',
  'jalapeño': 'Produce',
  'serrano': 'Produce',
  'poblano': 'Produce',
  'habanero': 'Produce',
  'zucchini': 'Produce',
  'broccoli': 'Produce',
  'cauliflower': 'Produce',
  'cabbage': 'Produce',
  'brussels sprout': 'Produce',
  'asparagus': 'Produce',
  'artichoke': 'Produce',
  'corn': 'Produce',
  'pea': 'Produce',
  'snow pea': 'Produce',
  'snap pea': 'Produce',
  'green bean': 'Produce',
  'bean sprout': 'Produce',
  'eggplant': 'Produce',
  'radish': 'Produce',
  'beet': 'Produce',
  'turnip': 'Produce',
  'parsnip': 'Produce',
  'rutabaga': 'Produce',
  'leek': 'Produce',
  'shallot': 'Produce',
  'green onion': 'Produce',
  'chive': 'Produce',
  'ginger': 'Produce',
  'fennel': 'Produce',
  'bok choy': 'Produce',
  'napa cabbage': 'Produce',
  'kohlrabi': 'Produce',
  'jicama': 'Produce',
  'daikon': 'Produce',
  'water chestnut': 'Produce',
  'bamboo shoot': 'Produce',
  'avocado': 'Produce',

  // Squash
  'butternut squash': 'Produce',
  'acorn squash': 'Produce',
  'delicata squash': 'Produce',
  'spaghetti squash': 'Produce',
  'kabocha': 'Produce',
  'hubbard squash': 'Produce',
  'honeynut squash': 'Produce',
  'yellow squash': 'Produce',
  'pattypan squash': 'Produce',
  'pumpkin': 'Produce',

  // Fruits
  'lemon': 'Produce',
  'lime': 'Produce',
  'orange': 'Produce',
  'grapefruit': 'Produce',
  'apple': 'Produce',
  'pear': 'Produce',
  'banana': 'Produce',
  'grape': 'Produce',
  'strawberry': 'Produce',
  'blueberry': 'Produce',
  'raspberry': 'Produce',
  'blackberry': 'Produce',
  'cranberry': 'Produce',
  'cherry': 'Produce',
  'peach': 'Produce',
  'plum': 'Produce',
  'apricot': 'Produce',
  'nectarine': 'Produce',
  'mango': 'Produce',
  'papaya': 'Produce',
  'pineapple': 'Produce',
  'kiwi': 'Produce',
  'watermelon': 'Produce',
  'cantaloupe': 'Produce',
  'honeydew': 'Produce',
  'fig': 'Produce',
  'pomegranate': 'Produce',
  'persimmon': 'Produce',
  'passion fruit': 'Produce',
  'dragon fruit': 'Produce',
  'lychee': 'Produce',
  'coconut': 'Produce',

  // Fresh herbs
  'basil': 'Produce',
  'cilantro': 'Produce',
  'parsley': 'Produce',
  'mint': 'Produce',
  'dill': 'Produce',
  'thyme': 'Produce',
  'rosemary': 'Produce',
  'sage': 'Produce',
  'oregano': 'Produce',
  'tarragon': 'Produce',
  'chervil': 'Produce',
  'marjoram': 'Produce',
  'lemongrass': 'Produce',
  'thai basil': 'Produce',

  // Citrus juice/zest
  'lemon juice': 'Produce',
  'lime juice': 'Produce',
  'orange juice': 'Produce',
  'lemon zest': 'Produce',
  'lime zest': 'Produce',
  'orange zest': 'Produce',

  // ========================================
  // DAIRY
  // ========================================

  'milk': 'Dairy',
  'butter': 'Dairy',
  'cream': 'Dairy',
  'heavy whipping cream': 'Dairy',
  'light cream': 'Dairy',
  'half and half': 'Dairy',
  'whipped cream': 'Dairy',
  'sour cream': 'Dairy',
  'cream cheese': 'Dairy',
  'yogurt': 'Dairy',
  'greek yogurt': 'Dairy',
  'cottage cheese': 'Dairy',
  'ricotta': 'Dairy',
  'mascarpone': 'Dairy',
  'egg': 'Dairy',
  'egg white': 'Dairy',
  'egg yolk': 'Dairy',

  // Cheeses
  'cheese': 'Dairy',
  'cheddar': 'Dairy',
  'mozzarella': 'Dairy',
  'parmesan': 'Dairy',
  'pecorino': 'Dairy',
  'gruyere': 'Dairy',
  'swiss cheese': 'Dairy',
  'gouda': 'Dairy',
  'brie': 'Dairy',
  'camembert': 'Dairy',
  'blue cheese': 'Dairy',
  'gorgonzola': 'Dairy',
  'feta': 'Dairy',
  'goat cheese': 'Dairy',
  'provolone': 'Dairy',
  'fontina': 'Dairy',
  'havarti': 'Dairy',
  'manchego': 'Dairy',
  'monterey jack': 'Dairy',
  'colby': 'Dairy',
  'asiago': 'Dairy',
  'burrata': 'Dairy',
  'halloumi': 'Dairy',
  'paneer': 'Dairy',
  'queso fresco': 'Dairy',
  'cotija': 'Dairy',
  'american cheese': 'Dairy',

  // Dairy alternatives (still in Dairy section for shopping convenience)
  'almond milk': 'Dairy',
  'oat milk': 'Dairy',
  'soy milk': 'Dairy',
  'coconut milk': 'Dairy',
  'cashew milk': 'Dairy',

  // Cultured dairy
  'buttermilk': 'Dairy',
  'kefir': 'Dairy',
  'clotted cream': 'Dairy',

  // Clarified/special butter
  'ghee': 'Dairy',

  // ========================================
  // MEAT & SEAFOOD
  // ========================================

  // Poultry
  'chicken': 'Meat & Seafood',
  'chicken breast': 'Meat & Seafood',
  'chicken thigh': 'Meat & Seafood',
  'chicken wing': 'Meat & Seafood',
  'chicken drumstick': 'Meat & Seafood',
  'ground chicken': 'Meat & Seafood',
  'turkey': 'Meat & Seafood',
  'ground turkey': 'Meat & Seafood',
  'duck': 'Meat & Seafood',
  'cornish hen': 'Meat & Seafood',

  // Beef
  'beef': 'Meat & Seafood',
  'steak': 'Meat & Seafood',
  'ground beef': 'Meat & Seafood',
  'beef mince': 'Meat & Seafood',
  'mince': 'Meat & Seafood',
  'minced meat': 'Meat & Seafood',
  'beef tenderloin': 'Meat & Seafood',
  'ribeye': 'Meat & Seafood',
  'sirloin': 'Meat & Seafood',
  'flank steak': 'Meat & Seafood',
  'skirt steak': 'Meat & Seafood',
  'brisket': 'Meat & Seafood',
  'chuck roast': 'Meat & Seafood',
  'short rib': 'Meat & Seafood',
  'beef stew meat': 'Meat & Seafood',
  'veal': 'Meat & Seafood',

  // Pork
  'pork': 'Meat & Seafood',
  'pork chop': 'Meat & Seafood',
  'pork tenderloin': 'Meat & Seafood',
  'pork shoulder': 'Meat & Seafood',
  'pork belly': 'Meat & Seafood',
  'ground pork': 'Meat & Seafood',
  'bacon': 'Meat & Seafood',
  'canadian bacon': 'Meat & Seafood',
  'pancetta': 'Meat & Seafood',
  'ham': 'Meat & Seafood',
  'prosciutto': 'Meat & Seafood',
  'sausage': 'Meat & Seafood',
  'italian sausage': 'Meat & Seafood',
  'chorizo': 'Meat & Seafood',
  'andouille': 'Meat & Seafood',
  'bratwurst': 'Meat & Seafood',
  'kielbasa': 'Meat & Seafood',
  'hot dog': 'Meat & Seafood',

  // Lamb
  'lamb': 'Meat & Seafood',
  'lamb chop': 'Meat & Seafood',
  'ground lamb': 'Meat & Seafood',
  'lamb mince': 'Meat & Seafood',
  'lamb shank': 'Meat & Seafood',
  'rack of lamb': 'Meat & Seafood',

  // Fish
  'salmon': 'Meat & Seafood',
  'tuna': 'Meat & Seafood',
  'cod': 'Meat & Seafood',
  'salt cod': 'Meat & Seafood',
  'halibut': 'Meat & Seafood',
  'tilapia': 'Meat & Seafood',
  'bass': 'Meat & Seafood',
  'chilean sea bass': 'Meat & Seafood',
  'branzino': 'Meat & Seafood',
  'mahi mahi': 'Meat & Seafood',
  'swordfish': 'Meat & Seafood',
  'snapper': 'Meat & Seafood',
  'trout': 'Meat & Seafood',
  'catfish': 'Meat & Seafood',
  'sardine': 'Meat & Seafood',
  'anchovy': 'Meat & Seafood',
  'mackerel': 'Meat & Seafood',
  'herring': 'Meat & Seafood',
  'sole': 'Meat & Seafood',
  'flounder': 'Meat & Seafood',

  // Shellfish
  'shrimp': 'Meat & Seafood',
  'scallops': 'Meat & Seafood',
  'clams': 'Meat & Seafood',
  'mussel': 'Meat & Seafood',
  'oyster': 'Meat & Seafood',
  'lobster': 'Meat & Seafood',
  'crab': 'Meat & Seafood',
  'calamari': 'Meat & Seafood',
  'octopus': 'Meat & Seafood',
  'crawfish': 'Meat & Seafood',

  // ========================================
  // BAKING
  // ========================================

  // Flours
  'flour': 'Baking',
  'whole wheat flour': 'Baking',
  'bread flour': 'Baking',
  'cake flour': 'Baking',
  'pastry flour': 'Baking',
  'almond flour': 'Baking',
  'coconut flour': 'Baking',
  'chickpea flour': 'Baking',
  'rice flour': 'Baking',
  'rye flour': 'Baking',
  'semolina': 'Baking',

  // Starches
  'cornstarch': 'Baking',
  'arrowroot': 'Baking',
  'tapioca starch': 'Baking',
  'potato starch': 'Baking',

  // Sugars
  'sugar': 'Baking',
  'brown sugar': 'Baking',
  'confectioners sugar': 'Baking',
  'turbinado sugar': 'Baking',
  'coconut sugar': 'Baking',

  // Sweeteners
  'honey': 'Baking',
  'maple syrup': 'Baking',
  'molasses': 'Baking',
  'light corn syrup': 'Baking',
  'agave': 'Baking',

  // Leavening
  'baking powder': 'Baking',
  'baking soda': 'Baking',
  'yeast': 'Baking',
  'active dry yeast': 'Baking',
  'instant yeast': 'Baking',
  'cream of tartar': 'Baking',

  // Extracts & flavorings
  'vanilla': 'Baking',
  'vanilla extract': 'Baking',
  'almond extract': 'Baking',
  'vanilla bean': 'Baking',

  // Chocolate & cocoa
  'chocolate': 'Baking',
  'chocolate chips': 'Baking',
  'dark chocolate': 'Baking',
  'milk chocolate': 'Baking',
  'white chocolate': 'Baking',
  'cocoa powder': 'Baking',
  'unsweetened chocolate': 'Baking',

  // Dried fruits for baking
  'raisins': 'Baking',
  'golden raisins': 'Baking',
  'dried currants': 'Baking',
  'dried cranberries': 'Baking',
  'dried apricot': 'Baking',
  'dates': 'Baking',
  'prunes': 'Baking',

  // ========================================
  // PANTRY
  // ========================================

  // Nuts & seeds
  'almond': 'Pantry',
  'walnut': 'Pantry',
  'pecan': 'Pantry',
  'cashew': 'Pantry',
  'pistachio': 'Pantry',
  'hazelnut': 'Pantry',
  'macadamia': 'Pantry',
  'pine nut': 'Pantry',
  'peanut': 'Pantry',
  'sunflower seed': 'Pantry',
  'pumpkin seed': 'Pantry',
  'sesame seed': 'Pantry',
  'flax seed': 'Pantry',
  'chia seed': 'Pantry',
  'hemp seed': 'Pantry',

  // Nut butters
  'peanut butter': 'Pantry',
  'almond butter': 'Pantry',
  'tahini': 'Pantry',

  // Legumes
  'white beans': 'Pantry',
  'pinto beans': 'Pantry',
  'kidney beans': 'Pantry',
  'black beans': 'Pantry',
  'chickpeas': 'Pantry',
  'split chickpea': 'Pantry',
  'lentils': 'Pantry',
  'french lentils': 'Pantry',
  'black lentils': 'Pantry',
  'red lentils': 'Pantry',
  'yellow lentils': 'Pantry',
  'fava beans': 'Pantry',
  'mung bean': 'Pantry',
  'pigeon pea': 'Pantry',

  // ========================================
  // PASTA & GRAINS
  // ========================================

  // Pasta
  'pasta': 'Pasta & Grains',
  'spaghetti': 'Pasta & Grains',
  'penne': 'Pasta & Grains',
  'rigatoni': 'Pasta & Grains',
  'fettuccine': 'Pasta & Grains',
  'linguine': 'Pasta & Grains',
  'angel hair': 'Pasta & Grains',
  'farfalle': 'Pasta & Grains',
  'fusilli': 'Pasta & Grains',
  'rotini': 'Pasta & Grains',
  'macaroni': 'Pasta & Grains',
  'orzo': 'Pasta & Grains',
  'lasagna': 'Pasta & Grains',
  'ravioli': 'Pasta & Grains',
  'tortellini': 'Pasta & Grains',
  'gnocchi': 'Pasta & Grains',
  'egg noodle': 'Pasta & Grains',
  'ramen': 'Pasta & Grains',
  'udon': 'Pasta & Grains',
  'soba': 'Pasta & Grains',
  'rice noodle': 'Pasta & Grains',
  'glass noodle': 'Pasta & Grains',

  // Rice
  'rice': 'Pasta & Grains',
  'white rice': 'Pasta & Grains',
  'brown rice': 'Pasta & Grains',
  'jasmine rice': 'Pasta & Grains',
  'basmati rice': 'Pasta & Grains',
  'arborio rice': 'Pasta & Grains',
  'sushi rice': 'Pasta & Grains',
  'wild rice': 'Pasta & Grains',

  // Grains
  'quinoa': 'Pasta & Grains',
  'couscous': 'Pasta & Grains',
  'israeli couscous': 'Pasta & Grains',
  'bulgur': 'Pasta & Grains',
  'farro': 'Pasta & Grains',
  'barley': 'Pasta & Grains',
  'oats': 'Pasta & Grains',
  'polenta': 'Pasta & Grains',
  'cornmeal': 'Pasta & Grains',
  'grits': 'Pasta & Grains',
  'buckwheat': 'Pasta & Grains',
  'millet': 'Pasta & Grains',
  'amaranth': 'Pasta & Grains',
  'teff': 'Pasta & Grains',
  'freekeh': 'Pasta & Grains',

  // ========================================
  // CONDIMENTS
  // ========================================

  // Oils
  'olive oil': 'Condiments',
  'neutral oil': 'Condiments',
  'vegetable oil': 'Condiments',
  'canola oil': 'Condiments',
  'sesame oil': 'Condiments',
  'coconut oil': 'Condiments',
  'avocado oil': 'Condiments',
  'peanut oil': 'Condiments',
  'walnut oil': 'Condiments',
  'truffle oil': 'Condiments',

  // Vinegars
  'vinegar': 'Condiments',
  'balsamic vinegar': 'Condiments',
  'red wine vinegar': 'Condiments',
  'white wine vinegar': 'Condiments',
  'apple cider vinegar': 'Condiments',
  'rice vinegar': 'Condiments',
  'sherry vinegar': 'Condiments',
  'champagne vinegar': 'Condiments',

  // Sauces
  'soy sauce': 'Condiments',
  'tamari': 'Condiments',
  'fish sauce': 'Condiments',
  'oyster sauce': 'Condiments',
  'hoisin': 'Condiments',
  'teriyaki': 'Condiments',
  'worcestershire': 'Condiments',
  'hot sauce': 'Condiments',
  'sriracha': 'Condiments',
  'tabasco': 'Condiments',
  'sambal': 'Condiments',
  'gochujang': 'Condiments',
  'miso': 'Condiments',
  'ketchup': 'Condiments',
  'mustard': 'Condiments',
  'dijon mustard': 'Condiments',
  'yellow mustard': 'Condiments',
  'whole grain mustard': 'Condiments',
  'mayonnaise': 'Condiments',
  'salsa': 'Condiments',
  'pesto': 'Condiments',
  'bbq sauce': 'Condiments',
  'tomato paste': 'Condiments',
  'tomato sauce': 'Condiments',
  'marinara': 'Condiments',

  // Dressings
  'ranch': 'Condiments',
  'italian dressing': 'Condiments',
  'caesar dressing': 'Condiments',
  'vinaigrette': 'Condiments',

  // Asian condiments
  'mirin': 'Condiments',
  'sake': 'Condiments',
  'shaoxing wine': 'Condiments',
  'toasted sesame oil': 'Condiments',

  // ========================================
  // SPICES & SEASONINGS
  // ========================================

  // Individual spices
  'salt': 'Spices & Seasonings',
  'kosher salt': 'Spices & Seasonings',
  'sea salt': 'Spices & Seasonings',
  'black pepper': 'Spices & Seasonings',
  'white pepper': 'Spices & Seasonings',
  'paprika': 'Spices & Seasonings',
  'smoked paprika': 'Spices & Seasonings',
  'cayenne pepper': 'Spices & Seasonings',
  'chili powder': 'Spices & Seasonings',
  'ancho chili powder': 'Spices & Seasonings',
  'chipotle powder': 'Spices & Seasonings',
  'red pepper flakes': 'Spices & Seasonings',
  'cumin': 'Spices & Seasonings',
  'coriander powder': 'Spices & Seasonings',
  'turmeric': 'Spices & Seasonings',
  'cinnamon': 'Spices & Seasonings',
  'nutmeg': 'Spices & Seasonings',
  'mace': 'Spices & Seasonings',
  'allspice': 'Spices & Seasonings',
  'cloves': 'Spices & Seasonings',
  'cardamom': 'Spices & Seasonings',
  'black cardamom': 'Spices & Seasonings',
  'ginger powder': 'Spices & Seasonings',
  'garlic powder': 'Spices & Seasonings',
  'onion powder': 'Spices & Seasonings',
  'mustard powder': 'Spices & Seasonings',
  'bay leaf': 'Spices & Seasonings',
  'star anise': 'Spices & Seasonings',
  'fennel seeds': 'Spices & Seasonings',
  'caraway': 'Spices & Seasonings',
  'carom seeds': 'Spices & Seasonings',
  'fenugreek': 'Spices & Seasonings',
  'fenugreek leaves': 'Spices & Seasonings',
  'dried fenugreek leaves': 'Spices & Seasonings',
  'saffron': 'Spices & Seasonings',
  'sumac': 'Spices & Seasonings',
  'asafoetida': 'Spices & Seasonings',
  'nigella seeds': 'Spices & Seasonings',
  'mustard seeds': 'Spices & Seasonings',
  'sesame seeds': 'Spices & Seasonings',
  'poppy seeds': 'Spices & Seasonings',
  'juniper berries': 'Spices & Seasonings',
  'tamarind': 'Spices & Seasonings',
  'dried mango powder': 'Spices & Seasonings',
  'red chili powder': 'Spices & Seasonings',

  // Dried herbs
  'dried oregano': 'Spices & Seasonings',
  'dried thyme': 'Spices & Seasonings',
  'dried basil': 'Spices & Seasonings',
  'dried rosemary': 'Spices & Seasonings',
  'dried dill': 'Spices & Seasonings',
  'dried parsley': 'Spices & Seasonings',
  'dried shiitake': 'Spices & Seasonings',
  'dried porcini': 'Spices & Seasonings',

  // Spice blends
  'italian seasoning': 'Spices & Seasonings',
  'herbs de provence': 'Spices & Seasonings',
  'garam masala': 'Spices & Seasonings',
  'curry powder': 'Spices & Seasonings',
  'five spice powder': 'Spices & Seasonings',
  'taco seasoning': 'Spices & Seasonings',
  'cajun seasoning': 'Spices & Seasonings',
  'old bay seasoning': 'Spices & Seasonings',
  'zaatar': 'Spices & Seasonings',
  'ras el hanout': 'Spices & Seasonings',
  'berbere': 'Spices & Seasonings',
  'harissa': 'Spices & Seasonings',
  'baharat': 'Spices & Seasonings',
  'shichimi togarashi': 'Spices & Seasonings',
  'furikake': 'Spices & Seasonings',
  'adobo seasoning': 'Spices & Seasonings',
  'sazon seasoning': 'Spices & Seasonings',
  'jerk seasoning': 'Spices & Seasonings',
  'pumpkin pie spice': 'Spices & Seasonings',
  'apple pie spice': 'Spices & Seasonings',
  'everything bagel seasoning': 'Spices & Seasonings',

  // ========================================
  // BEVERAGES (including cooking liquids)
  // ========================================

  'water': 'Beverages',
  'chicken broth': 'Beverages',
  'beef broth': 'Beverages',
  'vegetable broth': 'Beverages',
  'chicken stock': 'Beverages',
  'beef stock': 'Beverages',
  'vegetable stock': 'Beverages',
  'bone broth': 'Beverages',
  'wine': 'Beverages',
  'white wine': 'Beverages',
  'red wine': 'Beverages',
  'cooking wine': 'Beverages',
  'beer': 'Beverages',
  'coffee': 'Beverages',
  'tea': 'Beverages',
  'juice': 'Beverages',
  'apple juice': 'Beverages',
  'clam juice': 'Beverages',

  // ========================================
  // BAKERY
  // ========================================

  'bread': 'Bakery',
  'sourdough': 'Bakery',
  'baguette': 'Bakery',
  'ciabatta': 'Bakery',
  'focaccia': 'Bakery',
  'pita': 'Bakery',
  'naan': 'Bakery',
  'flatbread': 'Bakery',
  'tortilla': 'Bakery',
  'flour tortilla': 'Bakery',
  'corn tortilla': 'Bakery',
  'bagel': 'Bakery',
  'roll': 'Bakery',
  'bun': 'Bakery',
  'croissant': 'Bakery',
  'muffin': 'Bakery',
  'english muffin': 'Bakery',
  'brioche': 'Bakery',
  'breadcrumb': 'Bakery',
  'panko': 'Bakery',
  'croutons': 'Bakery',
  'graham cracker': 'Bakery',

  // ========================================
  // CANNED GOODS
  // ========================================

  'canned tomatoes': 'Canned Goods',
  'crushed tomatoes': 'Canned Goods',
  'diced tomatoes': 'Canned Goods',
  'whole peeled tomatoes': 'Canned Goods',
  'san marzano tomatoes': 'Canned Goods',
  'tomato puree': 'Canned Goods',
  'canned beans': 'Canned Goods',
  'canned chickpeas': 'Canned Goods',
  'canned corn': 'Canned Goods',
  'canned tuna': 'Canned Goods',
  'canned salmon': 'Canned Goods',
  'canned sardines': 'Canned Goods',
  'canned clams': 'Canned Goods',
  'canned coconut milk': 'Canned Goods',
  'canned pumpkin': 'Canned Goods',
  'olives': 'Canned Goods',
  'capers': 'Canned Goods',
  'artichoke hearts': 'Canned Goods',
  'roasted red peppers': 'Canned Goods',
  'sundried tomatoes': 'Canned Goods',
  'chipotle in adobo': 'Canned Goods',

  // ========================================
  // FROZEN
  // ========================================

  'frozen peas': 'Frozen',
  'frozen corn': 'Frozen',
  'frozen spinach': 'Frozen',
  'frozen berries': 'Frozen',
  'frozen fruit': 'Frozen',
  'frozen shrimp': 'Frozen',
  'ice cream': 'Frozen',
  'frozen pizza': 'Frozen',
  'frozen vegetables': 'Frozen',
};

/**
 * Get the category for an ingredient using the lookup table
 * Returns undefined if not found (caller should use fallback)
 */
export function getCategoryFromLookup(normalizedIngredient: string): string | undefined {
  return INGREDIENT_CATEGORIES[normalizedIngredient];
}

/**
 * Common pantry staples that most people already have at home.
 * Used to filter out these items from the shopping list by default.
 */
export const PANTRY_STAPLES = new Set([
  'salt',
  'kosher salt',
  'sea salt',
  'black pepper',
  'white pepper',
  'water',
  'cooking spray',
  'nonstick spray',
  'ice',
  'ice water',
]);
